import { describe, expect, it } from "vitest";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { runInNewContext } from "node:vm";
import * as esbuild from "esbuild";
import type * as CoreApi from "../src/index.js";
import type { Pack } from "../src/index.js";

const root = join(import.meta.dirname, "../../..");

/**
 * The root of core runs in a browser (an outside review found it Node-only: it read the schema and the packs from
 * disk at import time). Proof: bundle the root for the browser, which refuses any Node builtin, then run it in a
 * context with no `process` at all and validate models, a pack given in code, and a pack that needs installing.
 */
describe("core in a browser", () => {
  it("bundles for the browser with no Node builtin, and validates in a context without process", async () => {
    const out = await esbuild.build({
      entryPoints: [join(root, "packages/core/src/index.ts")],
      bundle: true, platform: "browser", format: "iife", globalName: "Core", write: false, logLevel: "silent",
    });
    const code = out.outputFiles[0]!.text;
    expect(code).not.toMatch(/require\("node:|from "node:/);
    const sandbox: Record<string, unknown> = { structuredClone, console, TextEncoder, TextDecoder, URL };
    runInNewContext(code, sandbox);
    const core = sandbox.Core as typeof CoreApi;
    expect(typeof sandbox.process).toBe("undefined");
    expect(Object.keys(core)).toContain("validate");
    // the schema is inside the bundle, not read from disk
    expect((core.schema as { $id: string }).$id).toContain("v1.json");
    const ok = core.validate({ components: [{ id: "a", kind: "database" }], connections: [], states: { use: "sre" } });
    expect(ok.ok, JSON.stringify(ok)).toBe(true); // the built-in states pack travels with the code
    // a provider pack: given in code it works; not given, the error says what to do in a browser
    const aws: Pack = { name: "aws", title: "AWS", version: "1", source: "test", terms: "theirs", kinds: { components: { s3: { glyph: "storage" } } } };
    expect(core.validate({ kinds: { use: ["aws"] }, components: [{ id: "a", kind: "aws:s3" }] }, { packs: [aws] }).ok).toBe(true);
    const missing = core.validate({ kinds: { use: ["aws"] }, components: [{ id: "a", kind: "aws:s3" }] });
    expect(missing.ok).toBe(false);
    if (!missing.ok) expect(missing.errors[0]!.toString()).toBe('/kinds/use/0: pack "aws" is not installed: add @orrery-diagrams/pack-aws (AWS Architecture Icons, Amazon Web Services\' icons under their terms), or in a browser give it to validate(model, { packs })');
    expect(core.packNames()).toEqual(["sre"]);
  }, 60_000);
  it("keeps the generated modules equal to their sources, so the schema file stays the reference", () => {
    const schema = JSON.parse(readFileSync(join(root, "packages/core/schema/v1.json"), "utf8"));
    const sre = JSON.parse(readFileSync(join(root, "packages/core/packs/sre.json"), "utf8"));
    const generated = readFileSync(join(root, "packages/core/src/generated.ts"), "utf8");
    expect(generated).toContain("// Generated by packages/core/scripts/embed.mjs");
    const modSchema = new Function(`${generated.replace(/^export const (\w+)/gm, "var $1").replace(/ as const;/g, ";")}; return { schema, builtInPacks };`)() as { schema: unknown; builtInPacks: Record<string, unknown> };
    expect(modSchema.schema).toEqual(schema);
    expect(modSchema.builtInPacks).toEqual({ sre });
  });
});
