// Writes packages/core/src/generated.ts: the JSON Schema and the built-in packs as code, so the root of core
// imports without touching the disk and runs in a browser (schema/v1.json and packs/*.json stay the sources and
// the published reference files). Runs before every build; test/browser.test.ts holds the output equal to them.
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const core = join(dirname(fileURLToPath(import.meta.url)), "..");
const schema = JSON.parse(readFileSync(join(core, "schema/v1.json"), "utf8"));
const packs = Object.fromEntries(readdirSync(join(core, "packs")).filter((f) => f.endsWith(".json")).sort().map((f) => [f.slice(0, -5), JSON.parse(readFileSync(join(core, "packs", f), "utf8"))]));
const out = `// Generated by packages/core/scripts/embed.mjs from schema/v1.json and packs/*.json; edit those, not this.
export const schema = ${JSON.stringify(schema)} as const;
export const builtInPacks = ${JSON.stringify(packs)} as const;
`;
writeFileSync(join(core, "src/generated.ts"), out);
console.log(`packages/core/src/generated.ts: the schema and ${Object.keys(packs).join(", ")}`);
