import { readdirSync, readFileSync } from "node:fs";
import { createRequire } from "node:module";
import { join } from "node:path";
import { pathToFileURL } from "node:url";
import type { ComponentKindDef, ConnectionKindDef, GroupKindDef, ShapeDef, StateDef } from "./types.js";

/**
 * A vocabulary a model pulls in by name (docs/PACKS.md): kinds bound to icons and frames, or states bound to looks.
 * `kinds.use` / `states.use` merge one in before the author's own definitions (R13). Kind names are prefixed
 * with the pack's name (`aws:s3`); state names are not. Generated by tools/packs/build.mjs.
 *
 * The tool ships `sre`, its own states vocabulary, under its own MIT licence. The providers' icon sets are not
 * the tool's to license: each is its own package, `@orrery-diagrams/pack-<name>`, carrying the provider's terms,
 * and a model that uses one needs it installed. In code, `validate(model, { packs })` takes packs directly.
 */
export interface Pack {
  name: string;
  title: string;
  version: string;
  source: string;
  /** The provider's terms for the icons, verbatim. */
  terms: string;
  kinds?: { components?: Record<string, ComponentKindDef>; groups?: Record<string, GroupKindDef>; connections?: Record<string, ConnectionKindDef> };
  states?: { default?: string; define?: Record<string, Omit<StateDef, "name">> };
  /** Shapes come in with `kinds.use`, prefixed like the kinds. */
  shapes?: { define?: Record<string, Omit<ShapeDef, "name">> };
}

/** The provider packs published beside the tool, each under its provider's terms; the install hint names them. */
export const PROVIDER_PACKS: Readonly<Record<string, { package: string; title: string; holder: string }>> = {
  aws: { package: "@orrery-diagrams/pack-aws", title: "AWS Architecture Icons", holder: "Amazon Web Services'" },
  azure: { package: "@orrery-diagrams/pack-azure", title: "Azure Public Service Icons", holder: "Microsoft's" },
  gcp: { package: "@orrery-diagrams/pack-gcp", title: "Google Cloud product icons", holder: "Google's" },
};

const BUILT_IN = join(import.meta.dirname, "../packs");
const NAME = /^[a-z][a-z0-9-]*$/;
const cache = new Map<string, Pack | undefined>();

/** Names of the packs that come with the tool itself, sorted. */
const builtIn = (): string[] => readdirSync(BUILT_IN).filter((f) => f.endsWith(".json")).map((f) => f.slice(0, -5)).sort();

/** An installed provider pack's file, looked for from the tool's own install and from the working project. */
function installedFile(name: string): string | undefined {
  const info = PROVIDER_PACKS[name];
  if (!info) return undefined;
  for (const from of [import.meta.url, pathToFileURL(join(process.cwd(), "package.json")).href]) {
    try { return createRequire(from).resolve(info.package); } catch { /* not here; try the next root */ }
  }
  return undefined;
}

/** A pack by name: given in code, built in, or installed as its own package. Files are read once. */
export function loadPack(name: string, given: readonly Pack[] = []): Pack | undefined {
  const own = given.find((p) => p.name === name);
  if (own) return own;
  if (!NAME.test(name)) return undefined;
  if (!cache.has(name)) {
    let pack: Pack | undefined;
    const file = builtIn().includes(name) ? join(BUILT_IN, `${name}.json`) : installedFile(name);
    try { pack = file ? (JSON.parse(readFileSync(file, "utf8")) as Pack) : undefined; } catch { pack = undefined; }
    cache.set(name, pack);
  }
  return cache.get(name);
}

/** Names of the packs a model may use here: built in, plus the provider packs that are installed. Sorted. */
export const packNames = (): string[] => [...new Set([...builtIn(), ...Object.keys(PROVIDER_PACKS).filter((n) => installedFile(n) !== undefined)])].sort();

/** Every pack name that exists, installed or not, for the "known" list. */
const knownNames = (): string[] => [...new Set([...builtIn(), ...Object.keys(PROVIDER_PACKS)])].sort();

/** How to get a provider pack that is not installed, and whose icons it brings. */
export function installHint(name: string): string {
  const info = PROVIDER_PACKS[name]!;
  return `pack "${name}" is not installed: add ${info.package} (${info.title}, ${info.holder} icons under their terms)`;
}

/** Why `loadPack(name)` gives nothing: unknown, or a provider pack that is not installed. Undefined when it loads. */
export function packProblem(name: string, given: readonly Pack[] = []): string | undefined {
  if (loadPack(name, given)) return undefined;
  return PROVIDER_PACKS[name] ? installHint(name) : `unknown pack "${name}"; known: ${knownNames().join(", ")}`;
}
