import { readdirSync, readFileSync } from "node:fs";
import { join } from "node:path";
import type { ComponentKindDef, ConnectionKindDef, GroupKindDef, StateDef } from "./types.js";

/**
 * A vocabulary shipped with the tool (docs/PACKS.md): kinds bound to icons and frames, or states bound to looks.
 * `kinds.use` / `states.use` merge one in before the author's own definitions (R13). Kind names are prefixed
 * with the pack's name (`aws:s3`); state names are not. Generated by tools/packs/build.mjs.
 */
export interface Pack {
  name: string;
  title: string;
  version: string;
  source: string;
  /** The provider's terms for the icons, verbatim. */
  terms: string;
  kinds?: { components?: Record<string, ComponentKindDef>; groups?: Record<string, GroupKindDef>; connections?: Record<string, ConnectionKindDef> };
  states?: { default?: string; define?: Record<string, Omit<StateDef, "name">> };
}

const DIR = join(import.meta.dirname, "../packs");
const cache = new Map<string, Pack | undefined>();

/** Names of the packs shipped with the tool, sorted. */
export const packNames = (): string[] => readdirSync(DIR).filter((f) => f.endsWith(".json")).map((f) => f.slice(0, -5)).sort();

/** A pack by name, or undefined if there is none. Read once. */
export function loadPack(name: string): Pack | undefined {
  if (!/^[a-z][a-z0-9-]*$/.test(name)) return undefined;
  if (!cache.has(name)) {
    let pack: Pack | undefined;
    try { pack = JSON.parse(readFileSync(join(DIR, `${name}.json`), "utf8")) as Pack; } catch { pack = undefined; }
    cache.set(name, pack);
  }
  return cache.get(name);
}
